# Generated by Django 5.2.4 on 2025-08-06 05:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.generate_short_uuid, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
