# Generated by Django 5.2.4 on 2025-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_secret_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
