# Generated by Django 5.2.4 on 2025-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_user_otp_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
