# Generated by Django 5.2.4 on 2025-08-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_refer_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, help_text='Unique referral code for the user', max_length=10, null=True, unique=True),
        ),
    ]
