# Generated by Django 5.2.4 on 2025-08-12 04:23

import django.db.models.deletion
import movieApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.CharField(default=movieApp.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('logline', models.CharField(blank=True, max_length=280)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('drama', 'Drama'), ('short', 'Short'), ('documentary', 'Documentary'), ('series', 'Series')], max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Poster or thumbnail URL', max_length=500, null=True)),
                ('trailer_url', models.URLField(blank=True, help_text='Trailer video URL', max_length=500, null=True)),
                ('full_film_url', models.URLField(blank=True, help_text='Full movie video URL', max_length=500, null=True)),
                ('status', models.CharField(choices=[('review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='review', max_length=12)),
                ('duration_s', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rent_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_hours', models.PositiveIntegerField(default=48)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filmmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movieApp.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_s', models.PositiveIntegerField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='movieApp.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['status'], name='movieApp_fi_status_625f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['type'], name='movieApp_fi_type_5b0e92_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['genre'], name='movieApp_fi_genre_i_6f215a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['user', 'film'], name='movieApp_wa_user_id_a01e61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('user', 'film')},
        ),
    ]
