# Generated by Django 5.2.4 on 2025-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='full_film_url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='film',
            name='full_film',
            field=models.FileField(blank=True, null=True, upload_to='full_film/'),
        ),
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer/'),
        ),
    ]
