# Generated by Django 5.2.4 on 2025-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_remove_film_full_film_url_remove_film_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='film',
            name='movieApp_fi_genre_i_6f215a_idx',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, to='movieApp.genre'),
        ),
    ]
