# Generated by Django 5.2.4 on 2025-08-12 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_remove_film_movieapp_fi_genre_i_6f215a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='full_film',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='full_film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trailer'),
        ),
    ]
