# Generated by Django 5.2.4 on 2025-08-12 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_alter_film_full_film_alter_film_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='full_film',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='full_film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trailer'),
        ),
    ]
