# Generated by Django 5.2.4 on 2025-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0006_alter_film_full_film_alter_film_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='full_film',
            field=models.FileField(blank=True, null=True, upload_to='full_film/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer/'),
        ),
    ]
